# Generated by Django 3.2.9 on 2021-12-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muiristapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muirist',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
