# Generated by Django 3.2.10 on 2021-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muiristapi', '0002_muirist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=2)),
                ('url', models.URLField()),
            ],
        ),
    ]
