# Generated by Django 3.2.10 on 2021-12-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muiristapi', '0003_parkdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='lists',
            field=models.ManyToManyField(related_name='Snippets', through='muiristapi.SnippetList', to='muiristapi.List'),
        ),
    ]
